name: website

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package dependencies
        run: |
          npm install
          npm run build
      - name: Build project
        run: npm run build
      - name: Run Tests to Collect Coverage
        run: npm test
      - name: Update Coverage Badge
        run: |
          npm install --no-save coveralls
          cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
          rm -rf ./coverage
      - name: Release to NPM using Semantic Release
        if: ${{ success() }}
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
